export enum Permission {
  // Company
  COMPANY_CREATE = 'COMPANY_CREATE',
  COMPANY_GET = 'COMPANY_GET',
  COMDELETE = 'COMPANY_UPDATE',
  COMPANY_DELETE = 'COMPANY_DELETE',

  // Employee
  EMPLOYEE_CREATE = 'EMPLOYEE_CREATE',
  EMPLOYEE_GET = 'EMPLOYEE_GET',
  EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE',
  EMPLOYEE_DELETE = 'EMPLOYEE_DELETE',

  // Group
  GROUP_CREATE = 'GROUP_CREATE',
  GROUP_GET = 'GROUP_GET',
  GROUP_UPDATE = 'GROUP_UPDATE',
  GROUP_DELETE = 'GROUP_DELETE',

  // User
  USER_CREATE = 'USER_CREATE',
  USER_GET = 'USER_GET',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
}
